teams:
  prismdb_team:
    description: "PrismDB Multi-Agent Team for NL to SQL Conversion"
    modes:
      - route    # Directs queries to specialized agents
      - coordinate   # Parallel task execution
      - collaborate  # Consensus-based complex query handling
    agents:
      orchestrator:
        type: "Orchestrator"
        description: "Coordinates agent workflow and manages shared context"
      
      nlu_agent:
        type: "NLUAgent"
        description: "Natural language understanding and intent classification"
        models:
          - openai/gpt-4-turbo
          - google/gemini-pro
      
      schema_agent:
        type: "SchemaAgent"
        description: "Database schema analysis and relationship mapping"
      
      sql_agent:
        type: "SQLAgent"
        description: "SQL generation with syntax validation"
        models:
          - google/gemini-pro
      
      execution_agent:
        type: "ExecutionAgent"
        description: "Safe query execution with timeout controls"
      
      visualization_agent:
        type: "VisualizationAgent"
        description: "Data visualization and insight generation"
      
      monitor_agent:
        type: "MonitorAgent"
        description: "Real-time thought process streaming"

# Configuration for each environment
environments:
  development:
    logging_level: "DEBUG"
    apis:
      openai:
        api_key: "${OPENAI_API_KEY}"
      gemini:
        api_key: "${GEMINI_API_KEY}"
    database:
      connection_string: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
      pool_size: 5
      max_overflow: 10
  
  production:
    logging_level: "INFO"
    apis:
      openai:
        api_key: "${OPENAI_API_KEY}"
      gemini:
        api_key: "${GEMINI_API_KEY}"
    database:
      connection_string: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
      pool_size: 10
      max_overflow: 20 